name = "simplesecscan-worker"
main = "src/index.js"
compatibility_date = "2023-10-30"

[site]
bucket = "./public"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "simplesecscan-uploads"

[[d1_databases]]
binding = "D1_DB"
database_name = "simplesecscan-results"
database_id = "66caa7d9-3cc5-4fb0-beef-1f7763460969"
